# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_auto_20171204_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('title_content', models.CharField(max_length=500)),
            ],
        ),
    ]
